development:
  adapter: mysql
  database: rannotate
  host: localhost
  username: root
  
test:
  adapter: mysql
  database: rannotate_test
  host: localhost
  username: root

production:
  adapter: mysql
  database: rannotate_prod
  username: rails
  password: rails
  socket: /var/lib/mysql/mysql.sock