development:
  adapter: mysql
  database: rannotate
  host: 
  username: rails
  password: rails
  port: 
  sslcert: 
  sslcapath: 
  sslcipher: 
  socket: /var/run/mysqld/mysqld.sock
  sslkey: 
  schema_order: 
  dbfile: 

test:
  adapter: mysql
  database: rannotate_test
  host: 
  username: rails
  password: rails
  port: 
  sslcert: 
  sslcapath: 
  sslcipher: 
  socket: localhost
  sslkey: 
  schema_order: 
  dbfile: 

production:
  adapter: mysql
  database: rannotate_production
  host: 
  username: root
  password: 
  port: 
  sslcert: 
  sslcapath: 
  sslcipher: 
  socket: /path/to/your/mysql.sock
  sslkey: 
  schema_order: 
  dbfile: 
