development:
  adapter: mysql
  database: rannotate
  host: 
  username: root
  password: 
  port: 
  sslcert: 
  sslcapath: 
  sslcipher: 
  socket: localhost
  sslkey: 
  schema_order: 
  dbfile: 

test:
  adapter: mysql
  database: rannotate_test
  host: 
  username: rails
  password: rails
  port: 
  sslcert: 
  sslcapath: 
  sslcipher: 
  socket: localhost
  sslkey: 
  schema_order: 
  dbfile: 

production:
  adapter: mysql
  database: rannotate_prod
  username: rails
  password: rails
  socket: /var/lib/mysql/mysql.sock
